config/routes.rb
SocialNetworking::Application.routes.draw do 
   
  devise_for :users
  
  resources :users

  resources :pages

  root :to => 'pages#index'

end

app/models/page.rb
class Page < ActiveRecord::Base

  validates :title, :body , :presence => true
  validates :title, :length => (3..255)
  validates :body, :length => { :maximum => 10000 }
  
  attr_accessible :title, :permalink, :body

  before_create :set_paramlink

  def to_param
    "#{id}-#{permalink}"
  end

  private

  def set_paramlink
    self.permalink = title.downcase.gsub(/\s+/, '_').gsub(/[^a-zA-Z0-9_]+/, '')
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :enabled, :profile
  
  validates :profile, :length => { :maximum => 1000 }
  validates :username, :uniqueness => true
  
  def email_with_username
    "#{username} <#{email}>"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_filter :load_page, :except => [:index, :new, :create]

  def index
    @pages = Page.all
  end

  def show   
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.new(params[:page])
    respond_to do |format|
      if @page.save
        format.html do
          redirect_to @page, :notice => "Page was successfully created."
        end
      else
        format.html do
          render "new"
        end
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html do
          redirect_to @page, :notice => "Page was successfully updated."
        end
      else
        format.html do
          render "new"
        end
      end
    end
  end

  def destroy
    @page.destroy
    respond_to do |format|
      format.html do
        redirect_to pages_path, :notice => "Page was successfully destroyed."
      end
    end
  end

  private

  def load_page
    if params[:id].present?
      @page = Page.find(params[:id])
    else
      raise "No id present"
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :load_user, :except => [:index, :new, :create]
  
  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    respond_to do |format|
      if @user.save
        format.html do
          redirect_to @user, :notice => "User was successfully created."
        end
      else
        format.html do
          render "new"
        end
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html do
          redirect_to @user, :notice => "User was successfully updated."
        end
      else
        format.html do
          render "new"
        end
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html do
        redirect_to users_path, :notice => "User was successfully destroyed."
      end
    end
  end

  def enable
    respond_to do |format|
      if @user.update_attribute(:enable, true)
        format.html do
          redirect_to users_path, :notice => "User was successfully enabled."
        end
      else
        format.html do
          render "new"
        end
      end
    end
  end

  private

  def load_user
    if params[:id].present?
      @user = User.find(params[:id])
    else
      raise "No id present"
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_menu.html.haml
%ul
  %li= link_to 'Home', '/'
  %li= link_to 'News', articles_path
  %li= link_to 'Forums', forums_path
  %li= link_to "Blogs", blogs_path
  %li= link_to 'Photos', photos_path
  %li= link_to 'Photo Tags', tags_path
- if true
  %li= current_user.username
  %li= link_to 'My Profile', edit_user_registration_path
  %li= link_to 'My Friends', friends_path(:user_id => current_user)
  %li= link_to 'New Blog Post', new_entry_path(:user_id => current_user)
  %li= link_to 'Blog Templates', usertemplates_path
  %li= link_to 'Upload Photo',new_user_photo_path(:user_id => current_user)
  %li= link_to 'Sign out', destroy_user_session_path, :method => :delete
  %li
    %hr{ :size=>"1", :width=>"90%", :align=>"left"}

app/views/layouts/application.html.haml
!!! XML
!!! 
%html{:lang => "en", "xml:lang" => "en", :xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %title SocialNetworking
    <!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script><![endif]-->
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          = link_to :class => "btn btn-navbar", data: { toggle: "collapse" ,  target: ".nav-collapse" } do
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "#", class: "brand" do
            Some store
          .nav-collapse
            %ul.nav
              %li= link_to "Link 1", "#"
              %li= link_to "Link 2", "#"
              %li= link_to "Link 3", "#"
              %li= link_to "Link 4", "#"
    .container
      - flash.each do |name, message|
        = link_to 'x', nil, class: "close", data: { dismiss: "alert" }
        .alert{ class: "alert-#{ name == :notice ? "success" : "error" }" }
          = message
      .row
        .span9
          = yield
        .span3
          %h2 About Us
          Lorem Ispum
            

:javascript
  var CKEDITOR_BASEPATH = '/assets/ckeditor/';

app/views/page/_form.html.haml
= simple_form_for @page, :html => { :class => 'form-horizontal' } do |f|
  = f.input :title
  = f.input :permalink
  = f.input :body
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), page_path, :class => 'btn'

app/views/page/edit.html.haml
- model_class = Page
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/page/index.html.haml
- model_class = Page
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:permalink)
      %th= model_class.human_attribute_name(:body)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @pages.each do |page|
      %tr
        %td= link_to page.id, page_path(page)
        %td= page.title
        %td= page.permalink
        %td= page.body
        %td=l page.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_page_path(page), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), page_path(page), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_page_path, :class => 'btn btn-primary'

app/views/page/new.html.haml
- model_class = Page
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/page/show.html.haml
- model_class = Page
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @page.title
%p
  %strong= model_class.human_attribute_name(:permalink) + ':'
  %br
  = @page.permalink
%p
  %strong= model_class.human_attribute_name(:body) + ':'
  %br
  = @page.body

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), page_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_page_path(@page), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), page_path(@page), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/pages/_form.html.haml
= simple_form_for @page do |f|
  = f.input :title
  = f.input :body
  = f.submit

app/views/pages/edit.html.haml
Edit Page
= render "form"

app/views/pages/index.html.haml
%ul
  = "Listing Pages"
  - @pages.each do |page|
    %li
      =link_to(page.permalink, page)

app/views/pages/new.html.haml
New Page
= render "form"

app/views/pages/show.html.haml
%h2= @page.title
%p=textilize(@page.body).html_safe

app/views/users/_form.html.haml
= simple_form_for @user, :html => { :class => 'form-horizontal' } do |f|
  = f.input :email
  = f.input :username
  = f.input :enabled
  = f.input :profile
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn'

app/views/users/_user.html.haml
%tr{:class => "#{cycle('odd', 'even')}"}
%td= user.username
%td= user.email

app/views/users/edit.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/users/index.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:email)
      %th= model_class.human_attribute_name(:sign_in_count)
      %th= model_class.human_attribute_name(:current_sign_in_at)
      %th= model_class.human_attribute_name(:last_sign_in_at)
      %th= model_class.human_attribute_name(:current_sign_in_ip)
      %th= model_class.human_attribute_name(:last_sign_in_ip)
      %th= model_class.human_attribute_name(:username)
      %th= model_class.human_attribute_name(:enabled)
      %th= model_class.human_attribute_name(:profile)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.id, user_path(user)
        %td= user.email
        %td= user.sign_in_count
        %td= user.current_sign_in_at
        %td= user.last_sign_in_at
        %td= user.current_sign_in_ip
        %td= user.last_sign_in_ip
        %td= user.username
        %td= user.enabled
        %td= user.profile
        %td=l user.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(user), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_user_path, :class => 'btn btn-primary'

app/views/users/new.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/users/show.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:email) + ':'
  %br
  = @user.email
%p
  %strong= model_class.human_attribute_name(:encrypted_password) + ':'
  %br
  = @user.encrypted_password
%p
  %strong= model_class.human_attribute_name(:reset_password_token) + ':'
  %br
  = @user.reset_password_token
%p
  %strong= model_class.human_attribute_name(:reset_password_sent_at) + ':'
  %br
  = @user.reset_password_sent_at
%p
  %strong= model_class.human_attribute_name(:remember_created_at) + ':'
  %br
  = @user.remember_created_at
%p
  %strong= model_class.human_attribute_name(:sign_in_count) + ':'
  %br
  = @user.sign_in_count
%p
  %strong= model_class.human_attribute_name(:current_sign_in_at) + ':'
  %br
  = @user.current_sign_in_at
%p
  %strong= model_class.human_attribute_name(:last_sign_in_at) + ':'
  %br
  = @user.last_sign_in_at
%p
  %strong= model_class.human_attribute_name(:current_sign_in_ip) + ':'
  %br
  = @user.current_sign_in_ip
%p
  %strong= model_class.human_attribute_name(:last_sign_in_ip) + ':'
  %br
  = @user.last_sign_in_ip
%p
  %strong= model_class.human_attribute_name(:username) + ':'
  %br
  = @user.username
%p
  %strong= model_class.human_attribute_name(:enabled) + ':'
  %br
  = @user.enabled
%p
  %strong= model_class.human_attribute_name(:profile) + ':'
  %br
  = @user.profile

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), users_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(@user), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(@user), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'